### ISSUE TITLE
`_marko_registerComponent is not a function` being thrown in vitest

### ISSUE THREAD

**Issue by vwong** [marko-js/marko#2698]
### Marko Version: 5.37.32 (and @marko/compiler@5.39.21)

New version broke vitest tests. It complains about:
```
TypeError: _marko_registerComponent is not a function.
```

This was working fine in marko@5.37.31 (thus @marko/compiler@5.39.20)

### Details

The tests all have the same structure:

```
import { render } from "@marko/testing-library";
import { describe, expect, it } from "vitest";
import template from "./template.marko"

describe("...", () => {
  it("...", () => {
    await render(template);
  });
});
```

I also have @marko/tags-api-preview if that makes any difference. With the exception of marko, everything is else is the latest as of now.

Strangely, I can run `@marko/run` in both dev and preview modes. It is just the tests that are failing.

### Your Environment

```
Node 22.16.0
Mac OS 15.5
"@marko/tags-api-preview": "^0.8.1",
"@marko/babel-utils": "6.6.3",
"@marko/run": "0.7.4",
"@marko/run-adapter-node": "2.0.2",
"@marko/testing-library": "6.2.0",
"@marko/type-check": "1.3.22",
"@marko/vite": "5.1.5",
"vitest": "3.2.0"
```

**Comment by DylanPiercey** [comment]
@vwong I believe this one is now addressed with latest `marko`. Could you double check?
