### PR TITLE
Fixes #495 - Support import destructuring using a colon.

### LINKED ISSUE #495: Is renaming destruction import suppose to work?
### Context
Renaming destruction imports are not working in `v4.0-beta.5` :

```
<import { client: twilio } from '../../lib/twilio.js' />
```

results in compilation error, while

```
<script template-helpers>
  const { client: twilio } = require('../../lib/twilio.js');
</script>
```

works fine...

### PR DESCRIPTION
**Pull request by austinkelleher**
Introduces colon alias destructuring support for `import`:

```javascript
<import { test: testAlias } from './test' } />
```

### CODE REVIEW

File: taglibs/core/util/parseImport.js [hunk 1]
```diff
@@ -34,16 +34,16 @@ function getVariableName(moduleSpecifier) {
 }
 
 function getNames(importSpecifier) {
-       var names = importSpecifier.split(/\bas\b/);
+   var names = importSpecifier.split(/\s*(?:\bas\b|:)\s*/);
```
Comment (austinkelleher) [inline taglibs/core/util/parseImport.js]: This is the real fix. The below changes are just spacing.
